# Generated by Django 4.2.7 on 2026-04-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Stationery', 'Stationery'), ('Clothing', 'Clothing'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
