# Generated by Django 4.2.7 on 2026-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
