# Generated by Django 4.2.7 on 2026-04-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.organization'),
        ),
    ]
