# Generated by Django 4.2.7 on 2026-04-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization'),
        ),
    ]
